-- Insert data into the books table with additional fields
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (1, 'The Great Gatsby', 'OLD_EDITIONS', 1099, 'F. Scott Fitzgerald', 'Scribner', '9780743273565', 'A novel set in the Jazz Age that tells the story of Jay Gatsby and his unrequited love for Daisy Buchanan.', 1925, 3, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (2, '1984', 'OLD_EDITIONS', 899, 'George Orwell', 'Secker & Warburg', '9780451524935', 'A dystopian novel that explores the dangers of totalitarianism and extreme political ideology.', 1949, 4, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (3, 'To Kill a Mockingbird', 'OLD_EDITIONS', 1299, 'Harper Lee', 'J.B. Lippincott & Co.', '9780061120084', 'A novel about racial injustice and moral growth in the Deep South during the 1930s.', 1960, 2, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (4, 'Moby Dick', 'OLD_EDITIONS', 1599, 'Herman Melville', 'Harper & Brothers', '9781503280786', 'The epic tale of Captain Ahab obsessive quest to hunt the white whale, Moby Dick.', 1851, 5, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (5, 'Pride and Prejudice', 'OLD_EDITIONS', 999, 'Jane Austen', 'T. Egerton', '9781503290563', 'A classic novel that explores themes of love, class, and social expectations in 19th-century England.', 1813, 1, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (6, 'The Catcher in the Rye', 'REGULAR', 1099, 'J.D. Salinger', 'Little, Brown and Company', '9780316769488', 'A story about teenage rebellion and alienation through the eyes of Holden Caulfield.', 1951, 3, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (7, 'Brave New World', 'REGULAR', 1199, 'Aldous Huxley', 'Chatto & Windus', '9780060850524', 'A dystopian novel that examines a futuristic society driven by technology and consumerism.', 1932, 4, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (8, 'The Hobbit', 'NEW_RELEASE', 1499, 'J.R.R. Tolkien', 'George Allen & Unwin', '9780547928227', 'A fantasy adventure about Bilbo Baggins and his journey to reclaim a treasure guarded by a dragon.', 1937, 2, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (9, 'Harry Potter and the Sorcerer Stone', 'NEW_RELEASE', 1999, 'J.K. Rowling', 'Bloomsbury', '9780439708180', 'The first book in the Harry Potter series, introducing the magical world of Hogwarts.', 1997, 5, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (10, 'The Alchemist', 'REGULAR', 1399, 'Paulo Coelho', 'HarperOne', '9780061122415', 'A philosophical novel about a shepherd journey to find his personal legend.', 1988, 1, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (11, 'The Road', 'NEW_RELEASE', 1299, 'Cormac McCarthy', 'Alfred A. Knopf', '9780307387899', 'A post-apocalyptic novel about a father and son journey through a desolate landscape.', 2006, 3, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (12, 'The Shining', 'REGULAR', 1499, 'Stephen King', 'Doubleday', '9780307743657', 'A horror novel about a family trapped in a haunted hotel during the winter.', 1977, 4, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (13, 'The Fault in Our Stars', 'NEW_RELEASE', 1099, 'John Green', 'Dutton Books', '9780525478812', 'A love story between two teenagers who meet at a cancer support group.', 2012, 2, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (14, 'The Hunger Games', 'NEW_RELEASE', 1599, 'Suzanne Collins', 'Scholastic Press', '9780439023481', 'A dystopian novel about a deadly competition in a post-apocalyptic world.', 2008, 5, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (15, 'Dune', 'REGULAR', 1899, 'Frank Herbert', 'Chilton Books', '9780441013593', 'A science fiction epic about politics, religion, and power on the desert planet Arrakis.', 1965, 1, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (16, 'The Kite Runner', 'REGULAR', 1299, 'Khaled Hosseini', 'Riverhead Books', '9781594631931', 'A story of friendship, betrayal, and redemption set in Afghanistan.', 2003, 3, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (17, 'Life of Pi', 'REGULAR', 1199, 'Yann Martel', 'Knopf Canada', '9780156027328', 'A tale of survival and spirituality as a boy is stranded on a lifeboat with a tiger.', 2001, 4, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (18, 'The Girl with the Dragon Tattoo', 'NEW_RELEASE', 1499, 'Stieg Larsson', 'Norstedts Förlag', '9780307949486', 'A mystery thriller about a journalist and a hacker investigating a decades-old disappearance.', 2005, 2, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (19, 'The Da Vinci Code', 'REGULAR', 1399, 'Dan Brown', 'Doubleday', '9780307474278', 'A mystery novel that explores religious history and secret societies.', 2003, 5, false);
INSERT INTO books (id, title, type, price, author, publisher, isbn, description, publication_year, quantity, sold) VALUES (20, 'The Book Thief', 'NEW_RELEASE', 1299, 'Markus Zusak', 'Picador', '9780375842207', 'A story narrated by Death about a young girl in Nazi Germany who finds solace in stealing books.', 2005, 1, false);

-- Insert data into the clients table
INSERT INTO clients (id, name, email, phone, address, loyalty_points) VALUES (1, 'John Doe', 'johndoe@example.com', '123-456-7890', '123 Main St, Springfield', 150);
INSERT INTO clients (id, name, email, phone, address, loyalty_points) VALUES (2, 'Jane Smith', 'janesmith@example.com', '987-654-3210', '456 Elm St, Shelbyville', 200);
INSERT INTO clients (id, name, email, phone, address, loyalty_points) VALUES (3, 'Alice Johnson', 'alicej@example.com', '555-123-4567', '789 Oak St, Capital City', 300);
INSERT INTO clients (id, name, email, phone, address, loyalty_points) VALUES (4, 'Bob Brown', 'bobbrown@example.com', '444-555-6666', '321 Pine St, Ogdenville', 120);
INSERT INTO clients (id, name, email, phone, address, loyalty_points) VALUES (5, 'Charlie Davis', 'charlied@example.com', '333-444-5555', '654 Maple St, North Haverbrook', 180);